version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    image: php:5.6-apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
