version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64  # プラットフォームを指定
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    image: php:7.1.15-apache
    platform: linux/amd64  # プラットフォームを指定
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64  # プラットフォームを指定
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
